### ISSUE TITLE
Character Shuffle Preference

### ISSUE THREAD

**Issue by duanemcguire** [EnigmaCurry/code-smore#7]
I like the shuffle because each character has equal weight in presentation.

Currently when shuffle is used, the specified character set is shuffled then that set is used repetitively until all trials are completed.   I would prefer that shuffle be performed on the set of characters over the number of trials.     

e.g.
-c asdf --trials 12

Current routine:
shuffle asdf and repeat over trials 
potential result:
sdafsdafsdaf

Preferred routine: 
shuffle asdfasdfasdf
potential result:
afsdfdsfdsaa

**Comment by EnigmaCurry** [comment]
Fixed in release [v0.1.29](https://github.com/EnigmaCurry/code-smore/releases/tag/v0.1.29)
